version: '3.7'
services:
  elastic:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail elastic:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3